arch: linear
aug: true
augmentation: RandomCrop
batch_size: 1024
ckpt: ''
ckpt_iter: -1
config_file: null
data: cifar
dist: dp
dist_address: '127.0.0.1:1235'
encode_layer: h
encoder_ckpt: ''
eval_freq: 980
finetune: false
iters: 9800
log_freq: 49
lr: 0.1
lr_schedule: linear
model_id: -1
n_augs_test: 50
n_augs_train: 10
name: ''
node_rank: 0
opt: sgd
precompute_emb_bs: -1
problem: eval
root: ''
save_freq: 100000000
scale_lower: 0.08
seed: -1
status: fail
test_bs: 1024
tmp: false
warmup: 0.0
weight_decay: 0.0001
workers: 2
world_size: 1 # a=1,b/bsz=:-0.8 87.15, -0.5 86.99, 0 87.33, 1 87.62, 4 87.00
 # a=1,b=:-0.8 90.86, -0.4 90.97, 0 90.97
# 0.1;  0.9111, 0.9120,0.9079,0.9072,0.9037