arch: ResNet50
aug: true
batch_size: 256
ckpt: ''
color_dist_s: 0.5
config_file: null
data: stl10_unlabeled
dist: ddp
dist_address: '127.0.0.1:1236'
eval_freq: 7800
iters: 39000
log_freq: 780
lr: 4.0
lr_schedule: warmup-anneal
multiplier: 2
name: 'reproduce-stl10'
node_rank: 0
opt: lars
problem: sim-clr
root: 'none'
save_freq: 7800
scale_lower: 0.08
seed: -1
sync_bn: true
temperature: 0.15
tmp: false
verbose: true
warmup: 0.01
weight_decay: 1.0e-06
workers: 8
world_size: 1
loss_type: 1
alpha: 0.5
bate: -0.2
